# Generated by Django 2.1.15 on 2024-02-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreid',
            name='score',
        ),
        migrations.DeleteModel(
            name='ScoreID',
        ),
    ]
