# Generated by Django 3.2.24 on 2024-02-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_auto_20240208_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.name', unique=True),
        ),
    ]
