# Generated by Django 3.2.24 on 2024-03-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_alter_score_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.name'),
        ),
    ]
