# Generated by Django 3.2.24 on 2024-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_alter_name_nadimak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='nadimak',
            field=models.CharField(max_length=100),
        ),
    ]
